name: "example_retail"
version: "1.0.0"
config-version: 2

profile: "example_retail"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data/seed_data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"

models:
  example_retail:
    staging:
      +materialized: view
      +schema: staging
    
    intermediate:
      +materialized: ephemeral
      +schema: intermediate
    
    marts:
      +materialized: table
      +schema: marts
      
      core:
        +tags: ["core"]
      
      reporting:
        +tags: ["reporting"]
